# import ROOT in batch mode                                                                                                                                                                                                                  
import sys                                                                                                                                                                                                                                   
oldargv = sys.argv[:]                                                                                                                                                                                                                        
sys.argv = [ '-b-' ]                                                                                                                                                                                                                         
import ROOT                                                                                                                                                                                                                                                                    
ROOT.gROOT.SetBatch(True)                                                                                                                                                                                                                                                      
sys.argv = oldargv                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                               
# load FWLite C++ libraries                                                                                                                                                                                                                                                    
ROOT.gSystem.Load("libFWCoreFWLite.so");                                                                                                                                                                                                                                       
ROOT.gSystem.Load("libDataFormatsFWLite.so");                                                                                                                                                                                                                                  
ROOT.AutoLibraryLoader.enable()                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                               
# load FWlite python libraries                                                                                                                                                                                                                                                 
from DataFormats.FWLite import Handle, Events                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                               
jets, jetLabel = Handle("std::vector<pat::Jet>"), "patJets"                                                                                                                                                                                                                
puid, puidLabel = Handle("edm::ValueMap<StoredPileupJetIdentifier>"), "pileupJetIdCalculatorNoCHS"                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                            
# open file (you can use 'edmFileUtil -d /store/whatever.root' to get the physical file name)                                                                                                                                                                                                                                                                                               
events = Events("file://testJetTools.root")
                                                                                                                                                                                                                                                                                                                                                                                            
for iev,event in enumerate(events):                                                                                                                                                                                                                                                                                                                                                         
    if iev >= 10: break                                                                                                                                                                                                                                                                                                                                                                     
    event.getByLabel(jetLabel, jets)                                                                                                                                                                                                                                                                                                                                                        
    event.getByLabel(puidLabel, puid)                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                            
    print "\nEvent %d: run %6d, lumi %4d, event %12d" % (iev,event.eventAuxiliary().run(), event.eventAuxiliary().luminosityBlock(),event.eventAuxiliary().event())                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                            
    # Jets (standard AK4)
    for i,j in enumerate(jets.product()):
        if j.pt() < 20: continue
	try: pdgId=j.genParton().pdgId()
	except: pdgId=0
	try: genJetMatch=j.genJet().pt()>0
	except: genJetMatch=0
	#print dir(puid.product().get(i))
        print "jet %3d: pt %5.1f (raw pt %5.1f), eta %+4.2f, parton pdgID %3d, genjet match %3d, pileup mva disc %+.2f, betaStar %+.2f" % (
            i, j.pt(), j.pt()*j.jecFactor('Uncorrected'), j.eta(), pdgId, genJetMatch, j.userFloat("pileupJetIdEvaluatorNoCHS:fullDiscriminant"), puid.product().get(i).betaStar())
